#spring.application.name=Inventry_backend_application
#server.port=2001
#
#resilience4j.ratelimiter.instances.apiLimiter.limitForPeriod=5
#resilience4j.ratelimiter.instances.apiLimiter.limitRefreshPeriod=1s
#resilience4j.ratelimiter.instances.apiLimiter.timeoutDuration=0s
#
#spring.datasource.hikari.maximum-pool-size=10
#spring.datasource.hikari.minimum-idle=5
#spring.datasource.hikari.connection-timeout=20000
#spring.datasource.hikari.idle-timeout=30000
#spring.datasource.hikari.max-lifetime=1200000
#
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.use_sql_comments=true
#spring.jpa.properties.hibernate.jdbc.batch_size=20
#spring.jpa.properties.hibernate.order_inserts=true
#spring.jpa.properties.hibernate.order_updates=true
#spring.jpa.properties.hibernate.multi_tenancy=SCHEMA
#
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.h2.console.settings.trace=false
#spring.h2.console.settings.web-allow-others=false
#
##TODO ->  java -jar app.jar --spring.profiles.active=dev || java -jar app.jar --spring.profiles.active=dev,aws  || -Dspring.profiles.active=dev
